trigger:
  branches:
    include:
      - stage

pool:
  vmImage: ubuntu-latest

steps:
  - task: vercel-deployment-task@1
    name: Deploy
    inputs:
      vercelProjectId: $(VERCEL_PROJECT_ID)
      vercelOrgId: $(VERCEL_ORG_ID)
      vercelToken: $(TOKEN_VERCEL)
      production: true